require '/app/init/tools.rb'
require '/app/init/init_anims.rb'

require '/app/components/components.rb'
require '/app/components/anim.rb'
require '/app/components/component_groups.rb'
require '/app/components/behavior.rb'
require '/app/components/player_behavior.rb'
require '/app/components/player_behavior2.rb'
require '/app/components/collider.rb'
require '/app/components/health.rb'
require '/app/component_registry.rb'

require '/app/systems/system.rb'
require '/app/systems/animation.rb'
require '/app/systems/render_static_solids.rb'
require '/app/systems/render_solids.rb'
require '/app/systems/render_sprites.rb'
require '/app/systems/collision.rb'
require '/app/systems/health.rb'
require '/app/systems/behavior.rb'
require '/app/systems/behavior_mods.rb'
require '/app/systems/cleanup.rb'

require '/app/factories/factory.rb'
require '/app/factories/being_factory.rb'
require '/app/factories/block_factory.rb'
require '/app/factories/mage_factory.rb'
require '/app/factories/sorceress_factory.rb'
require '/app/factories/steelclad_factory.rb'
require '/app/factories/adept_factory.rb'
require '/app/factories/spell_factory.rb'
require '/app/factories/spawner.rb'
require '/app/factories/trigger_factory.rb'

require '/app/world/level1.rb'
require '/app/world/world_init.rb'
require '/app/world/world_tick.rb'

require '/app/tick.rb'
